The idea of this notebook is to create a new merging method for two DataFrames when simName is not identical. \
We want one simulation per row and per simHash. Currently, there are two simulations per simHash for com8MotPSA (one simulation produces two output layers).

In [1]:
import pandas as pd
import pathlib
import pickle

from avaframe.in3Utils import cfgUtils

In [2]:
# This is the code for saving a pickle file if needed

# import pickle
# save dictionary to pickle file
# outDir = pathlib.Path(avaDir, 'Outputs', 'merge')
# fU.makeADir(outDir)
# with open(outDir / 'inputsDF_com1.pickle', 'wb') as fi:
#    pickle.dump(inputsDF, fi)

In [3]:
# set display options
pd.set_option('display.max_columns', None)

In [4]:
# load main configuration file
cfgMain = cfgUtils.getGeneralConfig()

avalancheDir = cfgMain['MAIN']['avalancheDir']

# 1.) Com1DFA

In [5]:
# use filePath if the pickle file is not located in the same directory as the notebook
#filePATH = pathlib.Path(avalancheDir, 'Outputs', 'merge', 'inputsDF_com1.pickle')

inputsDF_com1 = pickle.load(open('inputsDF_com1.pickle', "rb"))

In [6]:
# filePATH = pathlib.Path(avalancheDir, 'Outputs', 'merge', 'configurationDF_com1.pickle')

configurationDF_com1 = pickle.load(open('configurationDF_com1.pickle', "rb"))

In [7]:
# old/current merging method
inputsDF_merged_com1 = inputsDF_com1.reset_index().merge(configurationDF_com1, on=['simName', 'modelType']).set_index('index')

In [8]:
inputsDF_com1

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfv,ppr,pft
18081232691591762672,release1PF_711a0e02e9_C_L_res_dfa,release1PF,711a0e02e9,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
14112635156891491123,release1PF_b389de3b64_C_L_null_dfa,release1PF,b389de3b64,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
15664570086543819110,release1PF_6bb91ec177_C_L_null_dfa,release1PF,6bb91ec177,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
9318247764679838996,release1PF_854d16f423_C_L_res_dfa,release1PF,854d16f423,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...

In [9]:
configurationDF_com1

,simTypeList,modelType,resType,tSteps,initPartDistType,initialiseParticlesFromFile,particleFile,seed,iniStep,saveParticlesIni,subgridMixingFactorIni,dtIni,sphOptionIni,stopCritIni,stopCritIniSmall,maxIterations,bufferZoneFactor,additionallyFixedFactor,ftOptionIni,rho,rhoEnt,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,dt,tEnd,sphKernelRadiusTimeStepping,cMax,stopCritType,uFlowingThreshold,stopCrit,sphOption,minRKern,sphKernelRadius,viscOption,massPerParticleDeterminationMethod,massPerPart,deltaTh,sphKR0,nPPK0,aPPK,splitOption,thresholdMassSplit,distSplitPart,nSplit,cMinNPPK,cMaxNPPK,cMinMass,cMaxnMass,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,reprojMethodForce,reprojMethodPosition,reprojectionIterations,thresholdProjection,subgridMixingFactor,gravAcc,velMagMin,depMin,curvAccInFriction,curvAccInTangent,curvAccInGradient,centeredPosition,explicitFriction,frictModel,volClassSmall,volClassMedium,musamosat,tau0samosat,Rs0samosat,kappasamosat,Rsamosat,Bsamosat,musamosatsmall,tau0samosatsmall,Rs0samosatsmall,kappasamosatsmall,Rsamosatsmall,Bsamosatsmall,musamosatmedium,tau0samosatmedium,Rs0samosatmedium,kappasamosatmedium,Rsamosatmedium,Bsamosatmedium,muvoellmy,xsivoellmy,muvoellmyminshear,xsivoellmyminshear,tau0voellmyminshear,mucoulombminshear,tau0coulombminshear,mucoulomb,mu0wetsnow,xsiwetsnow,enthRef,TIni,entTempRef,cpIce,ResistanceModel,hRes,cRes,cResH,detrainment,detWithoutRes,detK,entEroEnergy,entShearResistance,entDefResistance,dam,restitutionCoefficient,nIterDam,dissDam,snowSlide,cohesionMaxStrain,minDistCohesion,cohesiveSurfaceTension,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,writePartToCSV,visuParticleProperties,contourResType,thresholdValue,createRangeTimeDiagram,TTdiagram,scenario,simName
854d16f423,res,dfa,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1,release1PF_854d16f423_C_L_res_dfa
711a0e02e9,res,dfa,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0,release1PF_711a0e02e9_C_L_res_dfa
b389de3b64,null,dfa,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0,release1PF_b389de3b64_C_L_null_dfa
6bb91ec177,null,dfa,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1,release1PF_6bb91ec177_C_L_null_dfa

In [10]:
inputsDF_merged_com1

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfv,ppr,pft,simTypeList,resType,tSteps,initPartDistType,initialiseParticlesFromFile,particleFile,seed,iniStep,saveParticlesIni,subgridMixingFactorIni,dtIni,sphOptionIni,stopCritIni,stopCritIniSmall,maxIterations,bufferZoneFactor,additionallyFixedFactor,ftOptionIni,rho,rhoEnt,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,dt,tEnd,sphKernelRadiusTimeStepping,cMax,stopCritType,uFlowingThreshold,stopCrit,sphOption,minRKern,sphKernelRadius,viscOption,massPerParticleDeterminationMethod,massPerPart,deltaTh,sphKR0,nPPK0,aPPK,splitOption,thresholdMassSplit,distSplitPart,nSplit,cMinNPPK,cMaxNPPK,cMinMass,cMaxnMass,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,reprojMethodForce,reprojMethodPosition,reprojectionIterations,thresholdProjection,subgridMixingFactor,gravAcc,velMagMin,depMin,curvAccInFriction,curvAccInTangent,curvAccInGradient,centeredPosition,explicitFriction,frictModel,volClassSmall,volClassMedium,musamosat,tau0samosat,Rs0samosat,kappasamosat,Rsamosat,Bsamosat,musamosatsmall,tau0samosatsmall,Rs0samosatsmall,kappasamosatsmall,Rsamosatsmall,Bsamosatsmall,musamosatmedium,tau0samosatmedium,Rs0samosatmedium,kappasamosatmedium,Rsamosatmedium,Bsamosatmedium,muvoellmy,xsivoellmy,muvoellmyminshear,xsivoellmyminshear,tau0voellmyminshear,mucoulombminshear,tau0coulombminshear,mucoulomb,mu0wetsnow,xsiwetsnow,enthRef,TIni,entTempRef,cpIce,ResistanceModel,hRes,cRes,cResH,detrainment,detWithoutRes,detK,entEroEnergy,entShearResistance,entDefResistance,dam,restitutionCoefficient,nIterDam,dissDam,snowSlide,cohesionMaxStrain,minDistCohesion,cohesiveSurfaceTension,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,writePartToCSV,visuParticleProperties,contourResType,thresholdValue,createRangeTimeDiagram,TTdiagram,scenario
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18081232691591762672,release1PF_711a0e02e9_C_L_res_dfa,release1PF,711a0e02e9,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0
14112635156891491123,release1PF_b389de3b64_C_L_null_dfa,release1PF,b389de3b64,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0
15664570086543819110,release1PF_6bb91ec177_C_L_null_dfa,release1PF,6bb91ec177,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1
9318247764679838996,release1PF_854d16f423_C_L_res_dfa,release1PF,854d16f423,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1

# 2.) Com8MoTPSA

In [11]:
# filePATH = pathlib.Path(avalancheDir, 'Outputs', 'merge', 'inputsDF_com8.pickle')

inputsDF_com8 = pickle.load(open('inputsDF_com8.pickle', "rb"))

In [12]:
# filePATH = pathlib.Path(avalancheDir, 'Outputs', 'merge', 'configurationDF_com8.pickle')

configurationDF_com8 = pickle.load(open('configurationDF_com8.pickle', "rb"))

In [13]:
inputsDF_com8

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfd,ppr,pfv
1581533278065055707,release1PF_183cbe6505_C_L_lay1_psa,release1PF,183cbe6505,C,lay1,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
15804278540942359921,release1PF_b582570d9b_C_L_lay1_psa,release1PF,b582570d9b,C,lay1,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
12866678855413360910,release1PF_183cbe6505_C_L_lay2_psa,release1PF,183cbe6505,C,lay2,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...
2492425747562597014,release1PF_b582570d9b_C_L_lay2_psa,release1PF,b582570d9b,C,lay2,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...

In [14]:
configurationDF_com8

,modelType,simTypeList,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,volClassSmall,volClassMedium,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,Gravitational acceleration (m/s^2),Density (kg/m^3),Rheology,Parameters,Dry-friction coefficient (-),Turbulent drag coefficient (-),Effective drag height (m),Centrifugal effects,Passive earth-pressure coeff. (-),Basal drag coeff. 0-2 (-),Basal drag coeff. 1-2 (-),Top drag coeff. (-),Conc_L2_Prof_Coeff_0 (-),Conc_L2_Prof_Coeff_1 (-),Conc_L2_Prof_Coeff_2 (-),Speed_L2_Prof_Coeff_0 (-),Speed_L2_Prof_Coeff_1 (-),Speed_L2_Prof_Coeff_2 (-),Forest effects,Tree drag coefficient (-),Modulus of rupture (MPa),Forest decay coefficient (m s),Entrainment L1,Entrainment L2,Erosion coefficient L1 (-),Bed strength profile,Bed friction coefficient (-),Bed density (kg/m^3),Deposition,Deposition density L1 (kg/m^3),Suspension model,Avalanche shear strength (Pa),Avalanche shear strength deposit (Pa),Decay coeff. snow s. s. suspension (-),Decay coeff. snow s. s. deposition (-),Entrainment coeff. m12 (-),Deposition rate 21 (m/s),Constant density L1,Evolving geometry,Simulation time (s),Minimum time step (s),Maximum time step (s),Output interval (s),Write velocity vectors,Write maximum pressure,Write instant. pressure,Minimum flow depth (m),Minimum speed (m/s),Momentum threshold (-),Initial CFL number (-),simName
183cbe6505,psa,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,0.739000,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,8.159325,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_183cbe6505_C_L_null_psa
b582570d9b,psa,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,1.233531,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,11.882906,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_b582570d9b_C_L_null_psa

In [15]:
# new merging method
# simHash is index, should not be index for merging
configurationDF_com8 = configurationDF_com8.reset_index().rename(columns={'index': 'simHash'})

# necessary because simNAme appears twice, leads to renaming of both columns when merging
configurationDF_com8 = configurationDF_com8.rename(columns={'simName': 'simName_renamed'})
#configurationDF_com8

In [16]:
inputsDF_merged_com8 = inputsDF_com8.reset_index().merge(configurationDF_com8, on=['simHash', 'modelType']).set_index('index')
inputsDF_merged_com8

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfd,ppr,pfv,simTypeList,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,volClassSmall,volClassMedium,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,Gravitational acceleration (m/s^2),Density (kg/m^3),Rheology,Parameters,Dry-friction coefficient (-),Turbulent drag coefficient (-),Effective drag height (m),Centrifugal effects,Passive earth-pressure coeff. (-),Basal drag coeff. 0-2 (-),Basal drag coeff. 1-2 (-),Top drag coeff. (-),Conc_L2_Prof_Coeff_0 (-),Conc_L2_Prof_Coeff_1 (-),Conc_L2_Prof_Coeff_2 (-),Speed_L2_Prof_Coeff_0 (-),Speed_L2_Prof_Coeff_1 (-),Speed_L2_Prof_Coeff_2 (-),Forest effects,Tree drag coefficient (-),Modulus of rupture (MPa),Forest decay coefficient (m s),Entrainment L1,Entrainment L2,Erosion coefficient L1 (-),Bed strength profile,Bed friction coefficient (-),Bed density (kg/m^3),Deposition,Deposition density L1 (kg/m^3),Suspension model,Avalanche shear strength (Pa),Avalanche shear strength deposit (Pa),Decay coeff. snow s. s. suspension (-),Decay coeff. snow s. s. deposition (-),Entrainment coeff. m12 (-),Deposition rate 21 (m/s),Constant density L1,Evolving geometry,Simulation time (s),Minimum time step (s),Maximum time step (s),Output interval (s),Write velocity vectors,Write maximum pressure,Write instant. pressure,Minimum flow depth (m),Minimum speed (m/s),Momentum threshold (-),Initial CFL number (-),simName_renamed
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1581533278065055707,release1PF_183cbe6505_C_L_lay1_psa,release1PF,183cbe6505,C,lay1,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,0.739000,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,8.159325,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_183cbe6505_C_L_null_psa
15804278540942359921,release1PF_b582570d9b_C_L_lay1_psa,release1PF,b582570d9b,C,lay1,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,1.233531,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,11.882906,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_b582570d9b_C_L_null_psa
12866678855413360910,release1PF_183cbe6505_C_L_lay2_psa,release1PF,183cbe6505,C,lay2,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,0.739000,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,8.159325,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_183cbe6505_C_L_null_psa
2492425747562597014,release1PF_b582570d9b_C_L_lay2_psa,release1PF,b582570d9b,C,lay2,psa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,True,,,,,,False,True,0.3,,,,,,False,True,,,,,,25000.0,60000.0,2,0.05,5,0.001,True,3,1,0.001,1.233531,../data/avaParabola,null,release1PF,,0,1.0,None,DEM_PF_Topo.asc,,11.882906,250.0,Voellmy,constant,0.4,0.001,0.0,yes,1.0,0.008,0.04,0.0001,1.3333,-0.66667,0.0,1.4,0.13333,-1.4,no,1.0,50.0,0.15,none,none,0.0,constant,0.0,140.0,yes,400.0,TJSM,0.0,0.0,1.0,1.0,0.0,0.5,yes,no,1000.0,0.001,0.1,1.0,no,yes,no,0.01,0.01,0.05,0.8,release1PF_b582570d9b_C_L_null_psa

# 3.) Compare old with new merging method for com1DFA

In [17]:
# old/current merged dataframe
inputsDF_merged_com1

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfv,ppr,pft,simTypeList,resType,tSteps,initPartDistType,initialiseParticlesFromFile,particleFile,seed,iniStep,saveParticlesIni,subgridMixingFactorIni,dtIni,sphOptionIni,stopCritIni,stopCritIniSmall,maxIterations,bufferZoneFactor,additionallyFixedFactor,ftOptionIni,rho,rhoEnt,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,dt,tEnd,sphKernelRadiusTimeStepping,cMax,stopCritType,uFlowingThreshold,stopCrit,sphOption,minRKern,sphKernelRadius,viscOption,massPerParticleDeterminationMethod,massPerPart,deltaTh,sphKR0,nPPK0,aPPK,splitOption,thresholdMassSplit,distSplitPart,nSplit,cMinNPPK,cMaxNPPK,cMinMass,cMaxnMass,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,reprojMethodForce,reprojMethodPosition,reprojectionIterations,thresholdProjection,subgridMixingFactor,gravAcc,velMagMin,depMin,curvAccInFriction,curvAccInTangent,curvAccInGradient,centeredPosition,explicitFriction,frictModel,volClassSmall,volClassMedium,musamosat,tau0samosat,Rs0samosat,kappasamosat,Rsamosat,Bsamosat,musamosatsmall,tau0samosatsmall,Rs0samosatsmall,kappasamosatsmall,Rsamosatsmall,Bsamosatsmall,musamosatmedium,tau0samosatmedium,Rs0samosatmedium,kappasamosatmedium,Rsamosatmedium,Bsamosatmedium,muvoellmy,xsivoellmy,muvoellmyminshear,xsivoellmyminshear,tau0voellmyminshear,mucoulombminshear,tau0coulombminshear,mucoulomb,mu0wetsnow,xsiwetsnow,enthRef,TIni,entTempRef,cpIce,ResistanceModel,hRes,cRes,cResH,detrainment,detWithoutRes,detK,entEroEnergy,entShearResistance,entDefResistance,dam,restitutionCoefficient,nIterDam,dissDam,snowSlide,cohesionMaxStrain,minDistCohesion,cohesiveSurfaceTension,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,writePartToCSV,visuParticleProperties,contourResType,thresholdValue,createRangeTimeDiagram,TTdiagram,scenario
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18081232691591762672,release1PF_711a0e02e9_C_L_res_dfa,release1PF,711a0e02e9,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0
14112635156891491123,release1PF_b389de3b64_C_L_null_dfa,release1PF,b389de3b64,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0
15664570086543819110,release1PF_6bb91ec177_C_L_null_dfa,release1PF,6bb91ec177,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1
9318247764679838996,release1PF_854d16f423_C_L_res_dfa,release1PF,854d16f423,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1

In [18]:
# simHash is index, should not be index for merging
configurationDF_com1_new = configurationDF_com1.reset_index().rename(columns={'index': 'simHash'})

# necessary because simNAme appears twice, leads to renaming of both columns when merging
configurationDF_com1_new = configurationDF_com1_new.rename(columns={'simName': 'simName_renamed'})
#configurationDF__com1_new

In [19]:
inputsDF_merged_com1_new = inputsDF_com1.reset_index().merge(configurationDF_com1_new, on=['simHash', 'modelType']).set_index('index')
inputsDF_merged_com1_new

,simName,releaseArea,simHash,simModified,simType,modelType,cellSize,pfv,ppr,pft,simTypeList,resType,tSteps,initPartDistType,initialiseParticlesFromFile,particleFile,seed,iniStep,saveParticlesIni,subgridMixingFactorIni,dtIni,sphOptionIni,stopCritIni,stopCritIniSmall,maxIterations,bufferZoneFactor,additionallyFixedFactor,ftOptionIni,rho,rhoEnt,relThFromShp,relThPercentVariation,relThRangeVariation,relThRangeFromCiVariation,relThDistVariation,relTh,relThFromFile,secRelArea,secondaryRelThFromShp,secondaryRelThPercentVariation,secondaryRelThRangeVariation,secondaryRelThRangeFromCiVariation,secondaryRelThDistVariation,secondaryRelTh,entThFromShp,entThIfMissingInShp,entThPercentVariation,entThRangeVariation,entThRangeFromCiVariation,entThDistVariation,entTh,dt,tEnd,sphKernelRadiusTimeStepping,cMax,stopCritType,uFlowingThreshold,stopCrit,sphOption,minRKern,sphKernelRadius,viscOption,massPerParticleDeterminationMethod,massPerPart,deltaTh,sphKR0,nPPK0,aPPK,splitOption,thresholdMassSplit,distSplitPart,nSplit,cMinNPPK,cMaxNPPK,cMinMass,cMaxnMass,interpOption,hmin,meshCellSize,meshCellSizeThreshold,cleanRemeshedRasters,resizeThreshold,methodMeshNormal,reprojMethodForce,reprojMethodPosition,reprojectionIterations,thresholdProjection,subgridMixingFactor,gravAcc,velMagMin,depMin,curvAccInFriction,curvAccInTangent,curvAccInGradient,centeredPosition,explicitFriction,frictModel,volClassSmall,volClassMedium,musamosat,tau0samosat,Rs0samosat,kappasamosat,Rsamosat,Bsamosat,musamosatsmall,tau0samosatsmall,Rs0samosatsmall,kappasamosatsmall,Rsamosatsmall,Bsamosatsmall,musamosatmedium,tau0samosatmedium,Rs0samosatmedium,kappasamosatmedium,Rsamosatmedium,Bsamosatmedium,muvoellmy,xsivoellmy,muvoellmyminshear,xsivoellmyminshear,tau0voellmyminshear,mucoulombminshear,tau0coulombminshear,mucoulomb,mu0wetsnow,xsiwetsnow,enthRef,TIni,entTempRef,cpIce,ResistanceModel,hRes,cRes,cResH,detrainment,detWithoutRes,detK,entEroEnergy,entShearResistance,entDefResistance,dam,restitutionCoefficient,nIterDam,dissDam,snowSlide,cohesionMaxStrain,minDistCohesion,cohesiveSurfaceTension,thresholdPointInPoly,relTh0,avalancheDir,simTypeActual,releaseScenario,thFromIni,relThId,relThThickness,relThCi95,DEM,relThFile,writePartToCSV,visuParticleProperties,contourResType,thresholdValue,createRangeTimeDiagram,TTdiagram,scenario,simName_renamed
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18081232691591762672,release1PF_711a0e02e9_C_L_res_dfa,release1PF,711a0e02e9,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0,release1PF_711a0e02e9_C_L_res_dfa
14112635156891491123,release1PF_b389de3b64_C_L_null_dfa,release1PF,b389de3b64,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.128919,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,0.739000,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,0,release1PF_b389de3b64_C_L_null_dfa
15664570086543819110,release1PF_6bb91ec177_C_L_null_dfa,release1PF,6bb91ec177,C,null,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,null,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,null,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1,release1PF_6bb91ec177_C_L_null_dfa
9318247764679838996,release1PF_854d16f423_C_L_res_dfa,release1PF,854d16f423,C,res,dfa,5.0,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,/home/lawine_naturgefahren/Fischbacher_Roland/...,res,ppr|pft|pfv,1,random,False,,12345,False,False,10.0,0.1,2,0.1,1.001,100,4,0.275,False,200,100,True,,,,,,False,False,True,,,,,,True,0.3,,,,,,0.1,400,False,0.02,kinEnergy,0.01,0.01,1,0.001,5,1,MPPDH,1250,0.25,5,15,-1.5,0,1.5,0.41,2,0.25,2.5,0.25,5,2,0.05,5,0.001,True,3,1,2,2,5,0.001,100.0,9.81,1.0e-6,1.0e-6,1,0,0,1,0,samosAT,25000.0,60000.0,0.187752,0,0.222,0.43,0.05,4.13,0.22,0,0.222,0.43,0.05,4.13,0.17,0,0.222,0.43,0.05,4.13,0.155,4000.0,0.155,4000.0,70,0.155,70,0.155,0.2,981.0,20000,-10,-10.0,2050.0,cRes,10,0.003,0.003,False,False,20,5000,0,0,True,1,1,1,0,0.2,1.0e-3,50000,0.001,1.233531,data/avaParabola,res,release1PF,relTh,0,1.0,None,DEM_PF_Topo.asc,,False,velocityMagnitude|m,ppr,1.0,False,True,1,release1PF_854d16f423_C_L_res_dfa

In [20]:
# drop redundant column
inputsDF_merged_com1_new = inputsDF_merged_com1_new.drop('simName_renamed', axis=1)

In [21]:
# compare if 2 dF the same
inputsDF_merged_com1_new.sort_index(axis=1).equals(inputsDF_merged_com1.sort_index(axis=1))

True

## 3.1) Result:

The new merging method uses simHash as the key instead of simName. \
This method does not solve the unique simHash problem. \
For com1DFA, the output from the new and old merging methods remains identical. \
When merging two DataFrames on simHash, be aware that other columns — such as simName — may exist in both DataFrames. This can cause automatic renaming (e.g., simName_x, simName_y) during the merge. \
To avoid this:
- One approach is to manually rename the simName column in one of the DataFrames before merging.
- Alternatively, if the simName values are identical across both DataFrames, you can drop one of the redundant columns after merging.